version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@tallerunonosql.hyk5p.mongodb.net/cursos?retryWrites=true&w=majority
