1.- Registro de usuario
@Post http://localhost:3000/users/register

{
  "userId": "123",
  "email": "user@example.com",
  "password": "securepassword"
}

mensaje esperado de respuesta 
{
  "message": "Usuario registrado exitosamente"
}

2.- Inicio de sesión 
@Post http://localhost:3000/users/login

{
  "email": "user@example.com",
  "password": "securepassword"
}

Mensaje de respuesta esperados

{
  "message": "Inicio de sesión exitoso",
  "userId": "1234",
  "email": "user@example.com"
}

{
  "statusCode": 404,
  "message": "Usuario no encontrado",
  "error": "Not Found"
}

{
  "statusCode": 401,
  "message": "Contraseña incorrecta",
  "error": "Unauthorized"
}


3.- Asigar cursos a un usuario 

@Post http://localhost:3000/users/123/courses

{
  "courseIds": ["6726e6da6d6f0576fde752a4", "6753aee1cd6787d9781f8149","6753af11cd6787d9781f814d"]
}

Posibles respuestas esperadas

200 OK

{
  "message": "Cursos asignados exitosamente",
  "courses": ["course1", "course2"]
}

4.- Obtener cursos del usuario 

@Get http://localhost:3000/users/123/courses

Respuesta esperada 

[
  {
    "id": "6726e6da6d6f0576fde752a4",
    "nombre": "Curso de Programación",
    "descripcionBreve": "Aprende a programar desde cero",
    "descripcionDetallada": "Este curso cubre los fundamentos de programación...",
    "imagen": "https://example.com/imagen1.jpg",
    "valoracion": 4.5,
    "cantidadInscritos": 100,
    "banner": "https://example.com/banner1.jpg"
  },
  {
    "id": "6753aee1cd6787d9781f8149",
    "nombre": "Curso de Programación Básica",
    "descripcionBreve": "Curso de programación desde cero",
    "descripcionDetallada": "Este curso cubre los fundamentos de programación, incluyendo variables, estructuras de control y conceptos básicos.",
    "imagen": "https://example.com/imagen1.jpg",
    "valoracion": 4.5,
    "cantidadInscritos": 100,
    "banner": "https://example.com/banner1.jpg"
  },
  {
    "id": "6753af11cd6787d9781f814d",
    "nombre": "Curso de Desarrollo Web",
    "descripcionBreve": "Aprende a crear páginas web desde cero",
    "descripcionDetallada": "Este curso te enseñará los fundamentos del desarrollo web, incluyendo HTML, CSS y JavaScript, para que puedas crear sitios web modernos y funcionales.",
    "imagen": "https://example.com/imagen2.jpg",
    "valoracion": 4.8,
    "cantidadInscritos": 200,
    "banner": "https://example.com/banner2.jpg"
  }
]


5.- Obtener el progreso de un curso 

@Get http://localhost:3000/progress/123

Respuesta esperada 

[
  {
    "courseId": "6753aee1cd6787d9781f8149",
    "progress": {
      "status": "INICIADO",
      "percentage": 0,
      "startDate": "2024-12-08",
      "totalClasses": 0,
      "classesCompleted": 0
    }
  },
  {
    "courseId": "6753af11cd6787d9781f814d",
    "progress": {
      "status": "INICIADO",
      "percentage": 0,
      "startDate": "2024-12-08",
      "totalClasses": 4,
      "classesCompleted": 0
    }
  },
  {
    "courseId": "6726e6da6d6f0576fde752a4",
    "progress": {
      "status": "INICIADO",
      "percentage": 0,
      "startDate": "2024-12-08",
      "totalClasses": 2,
      "classesCompleted": 0
    }
  }
]

6.- Actualizar progreso del curso

@Patch http://localhost:3000/progress/123/6726e6da6d6f0576fde752a4

Respuesta esperada 
{
  "message": "Progreso actualizado exitosamente",
  "progress": {
    "status": "EN CURSO",
    "percentage": 50,
    "startDate": "2024-12-08",
    "totalClasses": 2,
    "classesCompleted": 1
  }
}